theme: minima
title: Click With People
author: Larrie Knights
header_pages:
  - index.md
  - categories.html
  - contact.html
twitter_username: 512kilobytes
url: https://blog.larrieknights.com
defaults:
  - scope:
      path: ""
    values:
      image: /images/opengraph.png